### ISSUE TITLE
Run with rpicam noIR

### ISSUE THREAD

**Issue by HamHamFonFon** [adambaskerville/AstroPitography#2]
Hi,
Before install and use your application, i would like to know if it runs with the [rpi camera noIR v2](https://www.elektor.fr/raspberry-pi-noir-camera-module-v2) ?
Thank you :)

**Comment by adambaskerville** [comment]
I do not have the noIR v2 so unfortunately I cannot comment if it will work or not. However, I assume it will work given the noIR version 1 works fine with the picamera module AstroPitography uses; and so in theory the noIR v2 should work with picamera too.

If you do install and run it, it will be great to hear back if it works!
